theme: jekyll-theme-hacker
title: Blog of Prosad Das
description: This is where I write about my projects (both ongoing and past) and blog about latest discoveries in CRISPR-cas, genome editing and biotech.
