title: Prosad Kumar Das # your name (or website title) here
logo: "/images/cc_d__P.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently a research project associate at CSIR-IGIB located in New Delhi. I was a M.S. student at IISER-Kolkata where I majored in
  in Biology and minored in Computer Science. I am trying to develop gene-therapy platform based on CRISPR-Cas9 for familial monogenic disorders.
  <br><br>
  I really like and enjoy doing science, programming and reading pop-sci titles. I also have interests in behavioural genetics, social psychology, semiotics,
  religion, abstract math, EDM ;) and cinematography
  <br><br>
  <a href="https://www.linkedin.com/in/ProsadKumarDas">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
